name: houzi_package
description: LGS is real estate app.
version: 0.0.1
publish_to: none


environment:

  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  animate_icons: 2.0.0
  autocomplete_textfield: 2.0.1
  build_runner: 2.1.4
  cupertino_icons: 1.0.4
  dio: 4.0.3
  dio_cache_interceptor: 3.0.2
#  dio_http_cache: 0.3.0
  expandable: 5.0.1
  fancy_shimmer_image: 2.0.2
#  firebase_messaging: 13.0.2
  flutter_dialogs: 2.1.1
  flutter_staggered_grid_view: 0.4.1
  flutter_uploader: 3.0.0-beta.4
  #  flutter_uploader: 1.2.1
  flutter_widget_from_html: 0.8.2
  fluttertoast: 8.0.8
  flutter_local_notifications: 9.3.2
  location: 4.4.0
  geolocator: 7.7.1
  flutter_facebook_auth: 4.1.1
  html_unescape: 2.0.0
  hive_flutter: 1.1.0
  hive: 2.2.3
  hive_generator: 1.1.1
  image_picker: 0.8.6+4
  loading_gifs: 0.3.0
  loading_indicator: 3.0.2
  material_segmented_control: 3.1.2
  path_provider: 2.0.7
  pie_chart: 5.1.0
  provider: 6.0.1
  pull_to_refresh: 2.0.0
  shimmer: 2.0.0
  sliding_up_panel: 2.0.0+1
  smooth_page_indicator: 1.0.0+2
  timeago: 3.2.0
  toggle_switch: 1.3.0
  url_launcher: 6.1.10
  webview_flutter: 2.3.1
  shared_preferences: ^2.2.2

  sign_in_with_apple: 3.3.0
  crypto: 3.0.1
  google_mobile_ads: 2.2.0
  app_tracking_transparency: 2.0.2+4
  carousel_slider: 4.0.0

  share_plus: 4.1.0
  google_maps_cluster_manager: 3.0.0+1

  intl_phone_number_input: 0.7.1
  intl_phone_field: 3.1.0

  firebase_analytics: 10.0.4
  firebase_auth: 4.1.1
  google_maps_flutter: 2.4.0
  google_sign_in: 5.4.2

  flutter_cache_manager: 3.3.1

  #****===== IMPORTANT =====****
  # use 2.2.11 if flutter version < 3.7.0
  # use 2.2.23 if 3.7.0 < flutter version < 3.10.2
  pinput: 2.2.31


  path: 1.8.3

  firebase_core: 2.13.1
  flutter_rating_bar: 4.0.1
  package_info_plus: 4.0.2
  in_app_purchase: 3.0.1

  #****===== Updates =====****
  # use 0.18.0 if flutter version < 3.13.XX
  intl: 0.18.1
  flutter_localization: ^0.1.14
  flutter_launcher_icons: ^0.9.2


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


